In [1]:
from pathlib import Path
import pandas as pd
import mysql.connector

In [2]:
# load data

FILE_NAME = "demographic.csv"
DATA_PATH = Path("data") / "processed" / FILE_NAME

df = pd.read_csv(DATA_PATH)

df.head()

   CustomerId  Gender  Age     Salary  LocationId  Churned
0    15634602  Female   42  101348.88           2        1
1    15647311  Female   41  112542.58           6        0
2    15619304  Female   42  113931.57           4        1
3    15701354  Female   39   93826.63           1        0
4    15737888  Female   43   79084.10           4        0

In [3]:
# Create connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="BankChurn"
)

In [4]:
cursor = conn.cursor()

In [5]:
# Push demographic data to database

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO demographic (
            CustomerId,
            Gender,
            Age,
            Salary,
            LocationId,
            Churned
        )
        VALUES (%s, %s, %s, %s, %s, %s)
    """,
    (               
    int(row.CustomerId),
    row.Gender,
    int(row.Age),
    float(row.Salary),
    int(row.LocationId),
    int(row.Churned)
    ))
conn.commit()
print("Data inserted successfully")

Data inserted successfully

In [6]:
# load data

FILE_NAME = "location.csv"
DATA_PATH = Path("data") / "processed" / FILE_NAME

df = pd.read_csv(DATA_PATH)

df.head()

   LocationId Geography
0           1   Germany
1           2    France
2           3     Spain
3           4        UK
4           5    Canada

In [7]:
# Push location data to database

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO location (
            LocationId,
            Geography
        )
        VALUES (%s, %s)
    """,              
    (int(row.LocationId),
    row.Geography
    ))
conn.commit()
print("Data inserted successfully")

Data inserted successfully

In [ ]:
# To delete (only if needed)
# cursor.execute("DELETE FROM demographic")
# conn.commit()

In [9]:
# load data

FILE_NAME = "account.csv"
DATA_PATH = Path("data") / "processed" / FILE_NAME

df = pd.read_csv(DATA_PATH)

df.head()

   CustomerId  Tenure        Balance  NumProducts  HasCreditCard  IsActive
0    15634602       2  119827.493793            1              1         1
1    15647311       1   83807.860000            1              0         1
2    15619304       8  159660.800000            3              1         0
3    15701354       1  119827.493793            2              0         0
4    15737888       2  125510.820000            1              1         1

In [10]:
# Push account data to database

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO account (
            CustomerId,
            Tenure,
            Balance,
            NumProducts,
            HasCreditCard,
            IsActive
        )
        VALUES (%s, %s, %s, %s, %s, %s)
    """,              
    (int(row.CustomerId),
     int(row.Tenure),
     float(row.Balance),
     int(row.NumProducts),
     int(row.HasCreditCard),
     int(row.IsActive)
    ))
conn.commit()
print("Data inserted successfully")

Data inserted successfully